name: CI/CD Pipeline for Django

on:
  push:
    branches:
      - master  # Change this to your main branch      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Change this to your required Python version

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Create a temporary SSH key file
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # SSH into the EC2 instance and execute commands
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          cd ~/flexon-sales
          source venv/bin/activate
          cd ~/flexon-sales
          git remote -v
          git pull origin stg-backend --no-edit  # Change this to your main branch
          pip install -r requirements.txt
          pkill -f runserver  # Stop the current Django process
          nohup python3 manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &  # Restart in the background
        EOF
